version: "3.8"

services:
  
  front:
    image: walfvonfroy/tlc_image_front_v1.0:latest # image DockerHub
    container_name: container_front
    hostname: front
    ports:
      - "80:80" # port standard pour le protocole HTTP
      - "443:443" # port standard pour le protocole HTTPS
    depends_on:
      - phpmyadmin
      - etherpad
      - api
    restart: always 
      
  api:
    image: walfvonfroy/tlc_image_back_v2.0:latest
    container_name: container_api
    hostname: api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: on-failure
      
  db:
    image: mysql
    container_name: container_db
    hostname: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      interval: 4s
      timeout: 4s
      retries: 15
    volumes:
      - .api/src/main/resources/db/migration:/docker-entrypoint-initdb.d  


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: container_phpmyadmin
    hostname: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tlc 
      - MYSQL_PASSWORD=tlc
      - PMA_ARBITRARY=1
      - PMA_PMADB=phpmyadmin
      - PMA_HOST=db
    restart: always
    ports:
      - 8020:8020
    depends_on:
      - db
      
  etherpad:
    image: etherpad/etherpad:latest
    container_name: container_etherpad
    hostname: etherpad
    ports:
      - "9001:9001"
    volumes:
      - .api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
      
  mail:
    image: bytemark/smtp
    container_name: container_mail
    hostname: mail
    restart: always
    ports:
      - "25:25"
    depends_on:
      - api
      
volumes:
  db-data:


