version: "3.8"

services:
  
  front:
    image: walfvonfroy/image_front:2.0 # image DockerHub
    container_name: container_front
    hostname: front
    ports:
      - "15080:80" # port standard pour le protocole HTTP
      - "15443:443" # port standard pour le protocole HTTPS
    depends_on:
      - phpmyadmin
      - etherpad
      - api
    restart: always 
    volumes:
      - ./back.conf:/etc/nginx/conf.d/back.conf
      #- ./front/conf/etherpad.conf:/etc/nginx/conf.d/etherpad.conf
      #- ./front/conf/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf
      
  api:
    image: walfvonfroy/image_back:2.0
    container_name: container_api
    hostname: api
    depends_on:
      db:
        condition: service_healthy
#    ports:
#      - "15081:8080"
    restart: on-failure
      
  db:
    image: mysql
    container_name: container_db
    hostname: db
#    ports:
#      - "15306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      interval: 4s
      timeout: 4s
      retries: 15
    volumes:
      - ./migration:/docker-entrypoint-initdb.d  


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: container_phpmyadmin
    hostname: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tlc 
      - MYSQL_PASSWORD=tlc
      - PMA_ARBITRARY=1
      - PMA_PMADB=phpmyadmin
      - PMA_HOST=db
    restart: always
    ports:
      - 15020:8080
    depends_on:
      - db
      
  etherpad:
    image: etherpad/etherpad:latest
    container_name: container_etherpad
    hostname: etherpad
    ports:
      - "15091:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
      
  mail:
    image: bytemark/smtp
    container_name: container_mail
    hostname: mail
    restart: always
    ports:
      - "15025:25"
    depends_on:
      - api
      
volumes:
  db-data:


