version: "3.8"

services:

  front:
    image: walfvonfroy/image_front:8.0 # image DockerHub
    container_name: container_front
    hostname: front
    ports:
      - "15080:80" # port standard pour le protocole HTTP
    depends_on:
      - phpmyadmin
      - etherpad
      - api
    restart: always
    volumes:
      - ./back.conf:/etc/nginx/conf.d/back.conf

  api:
    image: walfvonfroy/image_back:8.0
    container_name: container_api
    hostname: api
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: mysql
    container_name: container_db
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      interval: 4s
      timeout: 4s
      retries: 15
    volumes:
      - ./migration:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: container_phpmyadmin
    hostname: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
      - PMA_ARBITRARY=1
      - PMA_PMADB=phpmyadmin
      - PMA_HOST=db
    restart: always
    depends_on:
      - db

  etherpad:
    image: etherpad/etherpad:latest
    container_name: container_etherpad
    hostname: etherpad
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    image: bytemark/smtp
    container_name: container_mail
    hostname: mail
    restart: always
    depends_on:
      - api

volumes:
  db-data:


