# dockerfile for image_front:v2.0 

# Stage 1 - BUILD

FROM node:10-alpine AS build-step
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build -- --outputPath=./dist/out

# Stage 2 - PROD

FROM nginx:1-alpine AS prod
COPY --from=build-step /app/dist/out/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80 443
