version: "3.8"
services:

  backend:
    image: walfvonfroy/tlc_image_back_v2.0:latest
    container_name: image_back
    hostname: api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
      
  db:
    hostname: db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      interval: 4s
      timeout: 4s
      retries: 15
    volumes:
      - db-data:/var/lib/mysql
    
  etherpad:
    hostname: etherpad
    image: etherpad/etherpad:latest
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    hostname: mail
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
      
volumes:
  db-data:

