version: "3.8"
services:

  backend:
    image: walfvonfroy/tlc_image_back_v2.0
    container_name: 
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=tlc
      - DB_USER=tlc
      - DB_PASSWORD=tlc
    depends_on:
      - db
      
  db:
    hostname: db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
#    volumes:
#      - ./db-data:/var/lib/mysql

  etherpad:
    hostname: etherpad
    image: etherpad/etherpad:latest
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    hostname: mail
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
      
volumes:
  db-data:

