version: "3.8"
services:
  
  front:
    image: walfvonfroy/tlc_image_front_v1.0:latest # image DockerHub
    container_name: container_front
    hostname: front
    restart: always
    ports:
      - "80:80" #port standard pour le protocole HTTP
      - "443:443" #port standard pour le protocole HTTPS
      
  backend:
    image: walfvonfroy/tlc_image_back_v2.0:latest
    container_name: container_back
    hostname: api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
      
  db:
    image: mysql
    container_name: conainer_db
    hostname: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      interval: 4s
      timeout: 4s
      retries: 15

  etherpad:
    image: etherpad/etherpad:latest
    container_name: container_etherpad
    hostname: etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    image: bytemark/smtp
    container_name: container_mail
    hostname: mail
    restart: always
    ports:
      - "2525:25"
      
volumes:
  db-data:


