version: "3.8"
services:

  backend:
    image: walfvonfroy/tlc_image_back_v2.0
    container_name: image_back
    hostname: api
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  db:
    hostname: db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc

  etherpad:
    hostname: etherpad
    image: etherpad/etherpad:latest
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    hostname: mail
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
      
volumes:
  db-data:

